エンジ部スキルマップ「正規表現
ShunichiBaba/beefee-training pull request #4
Opened 2023-01-06 05:33 UTC by ShunichiBaba

### 内容

### 対象ページ

2023-01-19 08:17 UTC, as-fujita requested changes

2023-01-19 08:17 UTC, as-fujita commented on regularExpressions/pregMatch.php
> +    echo '<h1>正しい電話番号でした</h1>';
# Comment
でっかく出てきてウケました

2023-01-19 08:17 UTC, as-fujita commented on regularExpressions/pregMatch.php
> +if(preg_match('/^(070|080|090|０７０|０８０|０９０)[-ー]\d{4}[-ー]\d{4}$/u',$_POST['telNum'])){
# IMO
先頭3文字について、こっちのほうがわかりやすいのでこのままでOKですが、
重複が少なくなるように書くとどうなるかコメントお願いします！

2023-01-19 08:17 UTC, as-fujita commented on regularExpressions/index.js
> +    e.preventDefault();
# Question
不要そう。POST送信しようとしてたときの名残かな？

2023-01-19 08:17 UTC, as-fujita commented on regularExpressions/index.js
> +
# IMO
エラーなしのとき何かわかる表示がほしいですね～

2023-01-19 08:17 UTC, as-fujita commented on regularExpressions/index.js
> +const regexAlpInt = /^(?=.*?[a-z])(?=.*?\d)[a-z\d]*$/i;
# IMO
もうちょいシンプルにできそうな…
`?=` は効果ないかな？

2023-01-19 08:17 UTC, as-fujita commented on regularExpressions/index.js
> +const regexChar = /^[a-z\d\-_/*+.,!#$%&()~|]*$/i;
# Question
`/i` にしてた意図ってなんでしょう？？

2023-01-20 01:17 UTC, ShunichiBaba commented on regularExpressions/pregMatch.php
> +if(preg_match('/^(070|080|090|０７０|０８０|０９０)[-ー]\d{4}[-ー]\d{4}$/u',$_POST['telNum'])){
'/^[0０](7|8|9|７|８|９)[0０][-ー]\d{4}[-ー]\d{4}$/u'
↑重複がないようにするとこうなるかと思います！

ファイルにもコメントアウトで記載しておきました。

2023-01-20 01:23 UTC, ShunichiBaba commented on regularExpressions/index.js
> +    e.preventDefault();
index.htmlでボタンを押したときの処理が書かれているので必要かと思います！
また、ページが更新されないようにしないと、結果が更新され、秒で結果が見られなくなってしまいます。

2023-01-20 02:00 UTC, ShunichiBaba commented on regularExpressions/index.js
> +
変数flagを用意し、パスワードが適切ではなかったならflagを立て、もしflagが立っていなかったら「正しいパスワードです」と表示するプログラムを書きました。

2023-01-20 04:20 UTC, ShunichiBaba commented on regularExpressions/index.js
> +const regexAlpInt = /^(?=.*?[a-z])(?=.*?\d)[a-z\d]*$/i;
> ?= は効果ないかな？
これがなくなるとうまくいかないので、効果がないわけではなさそうです！
しかし、もっと良い書き方がありましたので、修正し、最終的には以下となりました。
`/^[a-z\d!-~]*$/i`
`/[a-z!-~][\d]|[\d][a-z!-~]/i`


#メモ
`/[a-z]/`→a~zの文字が1つでもあればヒットする
`/[a-z][\d]/`→a～zの文字の後に数字があればヒットする
`/[a-z][\d]|[\d][a-z]/`→これだと↑上のやつが逆でもそのままでもヒットする

2023-01-20 04:23 UTC, ShunichiBaba commented on regularExpressions/index.js
> +const regexChar = /^[a-z\d\-_/*+.,!#$%&()~|]*$/i;
大文字と小文字の判定を無くし、小文字として扱われるようにするためにそうしました！

2023-01-24 00:41 UTC, as-fujita commented on regularExpressions/index.js
> +    e.preventDefault();
今のJSで完結している実装だとformタグ使わなくても良いなあってところが気になっています…！
formだけどJSでせき止めてPOST送信していない

ほんとはPOST送信したあとパスワードをDBに保存する処理につなげたいけど途中！の状態は、あまりよろしくないかなあ。
途中なことがわかるように「TODO:」のコメントを残すか、
いっそのことformタグを使わないほうが、後から他の人や未来の自分が見たときに別の変更を適用しやすいと思います！
このコメントは「formタグごと不要そう！」の意図でした！

2023-01-24 05:11 UTC, ShunichiBaba commented on regularExpressions/index.js
> +    e.preventDefault();
なるほど！
未完了のところをそのままにせずに必ず明記しておくことは大切なんですね。次からそうします。
コメントを追加してコミットしておきました。

2023-01-24 05:27 UTC, as-fujita commented on regularExpressions/index.js
> +const regexAlpInt = /^(?=.*?[a-z])(?=.*?\d)[a-z\d]*$/i;
修正前は、英字数字がどちらも入っているか？のバリデーションでしたが、記号かどうか判定している部分が入っているのは意図ありましたか？？

2023-01-24 05:30 UTC, as-fujita commented on regularExpressions/index.js
> +const regexChar = /^[a-z\d\-_/*+.,!#$%&()~|]*$/i;
英字部分のためか、理解です！

2023-01-24 05:35 UTC, as-fujita requested changes

2023-01-24 05:35 UTC, as-fujita commented on regularExpressions/index.js
> +const regexChar = /^[a-z\d!-~]*$/i;
# MUST
使用して良い記号判定部分、たとえば「@」が入ってもOK判定になっちゃってました！

2023-01-24 06:56 UTC, ShunichiBaba commented on regularExpressions/index.js
> +const regexAlpInt = /^(?=.*?[a-z])(?=.*?\d)[a-z\d]*$/i;
> ^(?=.*?[a-z]) ここの ^ があれば ?= 不要かな？と思ったのでした

たしかに、^があることで先頭をさしてくれるので、必要ないですね、、

> 記号かどうか判定している部分が入っているのは意図ありましたか？？

「1========3」の場合などといった英字数字が連続しないと失敗すると勘違いし記号も入れましたが、この例と同様に英字含めずに試行していたので失敗していました。

2023-01-24 06:59 UTC, ShunichiBaba commented on regularExpressions/index.js
> +const regexChar = /^[a-z\d!-~]*$/i;
a-zなどのハイフンを使った表現はASCIIコード表に従っていたんですね。
なるべく短くするためにつながっている部分はハイフンで括り、それ以外は個別で書くようにしました。
`/^[a-z\d!#-&(-/|~]*$/i`

2023-01-24 07:22 UTC, as-fujita commented on regularExpressions/index.js
> +const regexChar = /^[a-z\d!-~]*$/i;
`_` が漏れてるみたいでした！

2023-01-24 07:36 UTC, as-fujita commented on regularExpressions/index.js
> +const regexAlpInt = /^(?=.*?[a-z])(?=.*?\d)[a-z\d]*$/i;
着目点良いですね！修正してもらった正規表現だと「1========a」がNGになってしまいますね。
あと少し！修正してみましょうー！

2023-01-24 08:29 UTC, ShunichiBaba commented on regularExpressions/index.js
> +const regexAlpInt = /^(?=.*?[a-z])(?=.*?\d)[a-z\d]*$/i;
間の文字はなんでも良い（.*）を使用しました！
これなら、「1========a」もOKです！

2023-01-24 08:29 UTC, ShunichiBaba commented on regularExpressions/index.js
> +const regexChar = /^[a-z\d!-~]*$/i;
訂正しました！

2023-01-24 08:40 UTC, as-fujita commented on regularExpressions/index.js
> +const regexAlpInt = /^(?=.*?[a-z])(?=.*?\d)[a-z\d]*$/i;
良いですね！のこり `[\d]` の `[]` でくくるのは不要かな？

2023-01-24 09:09 UTC, ShunichiBaba commented on regularExpressions/index.js
> +const regexAlpInt = /^(?=.*?[a-z])(?=.*?\d)[a-z\d]*$/i;
[0~9]の場合必要ですが、\dの場合は不要ですね。
修正しました。

2023-01-24 09:23 UTC, merged