エンジ部スキルマップ「Apacheの設定」の課題提出
ShunichiBaba/beefee-training pull request #5
Opened 2023-01-24 09:12 UTC by ShunichiBaba

### 内容

- vhostsを使用してひとつのサーバ内でふたつのサイト（ドメイン）にアクセスできるようにする
- Apacheの設定ファイルでTEST_ENVという環境変数にLOCALという値を定義し、webアプリケーション側でTEST_ENVの値を取得、LOCALであればブラウザ上に「ローカル環境です」、PRODUCTIONであれば「本番環境です」と表示するスクリプトの作成
- 上記スクリプトを本番サーバにリリース
- http://example.local/index.phpにアクセスされたときにhttp://example.local/に301リダイレクトする処理をhtaccessに記述
- http://example.local/123/にアクセスされたときにhttp://example.local/index.php?q=123と同様の挙動をする処理をhtaccessに記述
- Apacheの設定を変更し、ブラウザから8080番ポートにアクセスしてWebページが表示されるようにする
- BASIC認証を利用して/admin/以下のURLにアクセスされた場合にユーザー名とパスワードによる認証を要求するようにする
- 特定IP以外から/admin/以下のURLにアクセスできないようにする
- 通常のaccess_log, error_logの他に、アクセスされた時刻のみを記録するログファイルを定義し、logs/test/内にtest_logというファイル名で書き込まれるようにする

課題の詳細は[こちら](https://sites.google.com/respect-pal.jp/engwiki/%E5%BF%85%E4%BF%AE%E8%AA%B2%E9%A1%8C/apache%E3%81%AE%E8%A8%AD%E5%AE%9Ahtaccess)

### 対象ページ

- 設定ファイルの変更事項をまとめたtxtファイル
  /beefee-training/apacheConfiguration/Apache_htaccess_baba.txt

### 想定する結果

それぞれ課題の通りです。
本番サーバには環境変数の課題しか設定していませんので、ほとんどローカル環境で行ったものとなります。

### 補足

本番サーバへのアクセス情報は、\\192.168.1.101\グループ共有\14.システム\Shunichi_Baba\研修用サーバアクセス情報\の中にあります。

2023-01-27 07:54 UTC, as-fujita requested changes

2023-01-27 07:54 UTC, as-fujita commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +[/var/www/html/test.php]
私のローカル環境で試したいので実際に使ったファイルも上げてほしいです！

2023-01-27 07:54 UTC, as-fujita commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +・/var/log/httpd/test/のパーミッションへ書き込みのみを有効にした
# Question
ここ具体的にどんな操作をしたでしょうか？？

デフォルトだと↓でエラーが出たってことだよねたぶん
```
    CustomLog "logs/test/test_log" test
```

2023-01-27 07:54 UTC, as-fujita commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +RewriteRule ^index.php$ http://example.local/ [L,R=301]
# SHOULD
このままでもここでは想定通りの動作をするんですが、
たとえば `one.example.com` がテスト環境だとして、このディレクトリに共通のコードを置いたときも動くように、汎用的な書き方にしたいです！

`http://one.example.com/index.php` にアクセスされたら `http://one.example.com/` に301リダイレクト
かつ
`http://example.local/index.php` にアクセスされたら `http://example.local/` に301リダイレクト

2023-01-27 07:54 UTC, as-fujita commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +RewriteRule ^123/$ /index.php/?q=123 [L,R=301]
# MUST
ここでは`http://example.local/123/` から **リダイレクトせず** 同じ挙動をするように設定してほしいです！

2023-01-27 07:54 UTC, as-fujita commented on regularExpressions/index.html
> +<!DOCTYPE html>
# Nits
関係ない差分出ちゃうのは最新のmainブランチをマージすれば解決するかな？

別課題で依存関係がなければ、mainブランチからブランチを切りましょう！

2023-01-27 07:54 UTC, as-fujita commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +・ファイヤーウォールの設定で、8080ポートも開放しました
# Nits
設定コマンドかfirewalleの設定状況リストを記載してほしいです！

2023-01-27 07:54 UTC, as-fujita commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +    DirectoryIndex test1.html test2.html
# Question
ここはどのサイト用の記述でした？
ふつうは index.php とか index.html を設定するので、全体に影響あるところで記述するとあとあと厄介かなと思いました…！

2023-01-27 07:54 UTC, as-fujita commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +    AuthUserFile /etc/httpd/htpasswd
# SHOULD
/etc/配下はシステムファイル置くところなので、ディレクトリ単位でかけるBasic認証のパスワード設定置くには適さないかなーと思います。

プログラムファイルを置くなら/var/配下で、Basic認証をかけたいディレクトリに配置した .htaccess に記載して、同じ階層に.htpasswdも置くことが多いかな。
パーミッション大事なので、どう設定したかはテキストファイルに記載してほしいです！

全体的に現在のディレクトリ構成も知りたい…

2023-01-27 07:54 UTC, as-fujita commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +    Require ip 122.217.37.50
# Comment
IP制限は .htaccess に書く場合もあればApacheのconf側に書く場合もどっちもあります。
レンタルサーバーだとApacheのconfをいじれないことも多いので、FTPアップロードできる範囲のファイルで設定できる .htaccess で設定されがちですね。

2023-01-30 01:49 UTC, ShunichiBaba commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +[/var/www/html/test.php]
こちらとりあえずコミットプッシュしました。

2023-01-30 02:00 UTC, ShunichiBaba commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +・/var/log/httpd/test/のパーミッションへ書き込みのみを有効にした
```
<IfModule log_config_module>
    LogFormat "%t" test
    CustomLog "logs/test/test_log" test
</IfModule>
```

LogFormatを使用して、リクエストされた時刻のみを記録するtestというログを作成し、CustomLogを使用してlogs/test/test_logの中にtestというログを書き込むように指示しました。

> chmod 222 /var/log/httpd/test/test_log

また上記コマンドをしようして、test_logのパーミッションに書き込みを有効にしました。「-rw-r--r--」となっています。

2023-01-30 06:13 UTC, ShunichiBaba commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +RewriteRule ^123/$ /index.php/?q=123 [L,R=301]
`RewriteRule ^123/$ /index.php?q=123 [L]`

こちらはリダイレクトせずにリライトで実装しました。

2023-01-30 06:51 UTC, ShunichiBaba commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +・ファイヤーウォールの設定で、8080ポートも開放しました
> [vagrant@vagrant ~]$ sudo firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0 eth1
  sources:
  services: ssh dhcpv6-client http
  ports: 8080/tcp
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

こちら追記しました。

2023-01-30 06:54 UTC, ShunichiBaba commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +    DirectoryIndex test1.html test2.html
https://respect-pal.slack.com/archives/C02UGPFBSN8/p1673944733071819

こちらのときのものです。
index.htmlという名前に変更するか、DirectoryIndexで指定するかと教わりました。
今回の課題とは関係がないので、削除しておきます。

2023-01-31 00:18 UTC, ShunichiBaba commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +    AuthUserFile /etc/httpd/htpasswd
/var/www/html/admin/で.htaccessと.htpasswdを設置しました。
パーミッションもテキストファイルに記載しました。

2023-02-01 02:32 UTC, ShunichiBaba commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +RewriteRule ^index.php$ http://example.local/ [L,R=301]
```
#RewriteCond %{HTTP_HOST} ^one\.example\.com$
#RewriteRule ^index.php$ http://one.example.com/ [L,R=301]
RewriteCond %{QUERY_STRING} !q=\d*
RewriteRule ^index.php$  / [L,R=301]
```

こんな感じで/var/www/html/.htaccessに書き込んで見たのですが、one.example.comのほうはindex.phpにリダイレクトされなかったです。

```
RewriteEngine On
RewriteRule ^index.php$  / [L,R=301]
```

ですので、今回は/var/www/vhosts/test1/.htaccessに↑を書き込むことで実現させました。

2023-02-01 02:36 UTC, ShunichiBaba commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +    Require ip 122.217.37.50
こちらBasic認証との共存ができていなかったので、.htaccessに書き直しました。

先日[こちらのスレッド](https://respect-pal.slack.com/archives/C04LM4SKMU6/p1675149085050689?thread_ts=1675143516.491849&cid=C04LM4SKMU6)で相談させていただいたように、AWS上で実行結果がうまくいったので、AWS側の/var/www/html/admin/.htaccessの中身をvagrant上にコピーしたものを提出しました。

中身は以下のようになっています
```
#ip制限とBasic認証を共存させるために、RequireAllとRequireAnyで括りました。
<RequireAll>
   
        #社内IPのみアクセス可
        <RequireAny>
            Require ip 122.217.37.50 
        </RequireAny>

        #Basic認証
        AuthType Basic
        AuthName "Auth"
        AuthUserFile /var/www/html/admin/.htpasswd
        Require valid-user
</RequireAll>
```

2023-02-01 05:13 UTC, as-fujita commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +    DirectoryIndex test1.html test2.html
なるほど！
今回の課題と関係ないので削除でOKですが、
もし設定するのであれば「one.example.com」「second.example.com」それぞれの場合のみ適用されるようにしたいですね。

2023-02-01 07:17 UTC, as-fujita commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +・/var/log/httpd/test/のパーミッションへ書き込みのみを有効にした
222 なのか 「-rw-r--r--」（644）なのかどっちに設定する意図でしたか？？
ログに書き込みするLinuxユーザーが書き込めて、書き込まないLinuxユーザーは書き込めない（閲覧はできてよい）設定にしたいですね。

2023-02-01 07:23 UTC, as-fujita commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +RewriteRule ^index.php$ http://example.local/ [L,R=301]
>こんな感じで/var/www/html/.htaccessに書き込んで見たのですが、one.example.comのほうはindex.phpにリダイレクトされなかったです。

`/var/www/html/.htaccess` はディレクトリの親子関係から外れてるので `/var/www/vhosts/test1/` 配下には影響与えないですね！

`one.example.com` ドメインはたとえで、意図はサイトのドメインを決め打ちしない書き方にしてほしい、ってことだったので「/」に変更でばっちりです！

2023-02-01 07:25 UTC, as-fujita commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +    AuthUserFile /etc/httpd/htpasswd
ばっちりですね！

2023-02-01 07:43 UTC, as-fujita commented on apacheCnfiguration/Apache_htaccess_baba.txt
> +・/var/log/httpd/test/のパーミッションへ書き込みのみを有効にした
644とのこと！

2023-02-01 07:43 UTC, merged